DROP TABLE PAYMENT
DROP SEQUENCE PAYMENTSEQ
DROP SEQUENCE BOARDnoSQ
DROP SEQUENCE GROUPnoSQ
DROP TABLE QUEBOARD
DROP TABLE ZZIM
DROP SEQUENCE ZZIMSEQ
DROP TABLE LOGIN
DROP SEQUENCE LOGINSEQ
DROP TABLE RECIPE_INFO
DROP SEQUENCE RECIPE_ID_SEQ
DROP SEQUENCE VIEW_SEQ
DROP TABLE RECIPE_MATERIAL
DROP TABLE MY_REFRIGERATOR
DROP TABLE RECIPE_PROCESS


--결제테이블--
CREATE SEQUENCE PAYMENTSEQ;

CREATE TABLE PAYMENT(
   PAYSEQ NUMBER PRIMARY KEY,
   ID VARCHAR2(100) NOT NULL,
   MATER VARCHAR2(100) NOT NULL,
   PRICE NUMBER NOT NULL,
   PAYDATE DATE NOT NULL,
   PLACE VARCHAR2(1000) NOT NULL
);
--테스트용
INSERT INTO PAYMENT VALUES(PAYMENTSEQ.NEXTVAL,'ASDF','김치','1000',SYSDATE,'서울특별시 중랑구 망우동');

SELECT * FROM PAYMENT;






--게시판테이블----
CREATE SEQUENCE BOARDNOSQ;
CREATE SEQUENCE GROUPNOSQ; 

CREATE TABLE QUEBOARD(
BOARDNO NUMBER PRIMARY KEY,
GROUPNO NUMBER NOT NULL,
GROUPSQ NUMBER NOT NULL,
REPLYNO NUMBER ,
SECFLAG VARCHAR2(2) ,
WRITER VARCHAR2(2000) NOT NULL,
TITLE VARCHAR2(3000),
CONTENT CLOB,
REGDATE DATE NOT NULL,
CONSTRAINT SECFLAG_CHK CHECK (SECFLAG IN('Y','N'))
);
--테스트용
INSERT INTO QUEBOARD VALUES(BOARDNOSQ.NEXTVAL,GROUPNOSQ.NEXTVAL,1,0,'N','asdf','안녕하세요','문의글입니다.',SYSDATE);
SELECT * FROM QUEBOARD;




--로그인테이블
CREATE SEQUENCE LOGINSEQ;

CREATE TABLE LOGIN(
   USERSEQ NUMBER PRIMARY KEY,
   NAME VARCHAR2(100) NOT NULL,
   ID VARCHAR2(100) NOT NULL,
   PW VARCHAR2(50) NOT NULL,
   PHONE VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) NOT NULL,
   ADDR VARCHAR2(1000) NOT NULL,
   ZONECODE VARCHAR2(1000) NOT NULL,
   ENABLED VARCHAR2(2) NOT NULL,
   ROLE VARCHAR2(100) NOT NULL,
   CONSTRAINT CON_ID UNIQUE(ID)
);
--테스트용계정
INSERT INTO LOGIN
VALUES(LOGINSEQ.NEXTVAL,'조수연','aa','aa','010-6398-7668','ASDF@ASDF','경기도 성남시 중원구','02055','Y','USER');
--관리자
INSERT INTO LOGIN
VALUES(LOGINSEQ.NEXTVAL,'정햇나라','ASDF','ASDF','01012345678','ASDF@ASDF','경기도 성남시 중원구','13183','Y','ADMIN');

SELECT * FROM LOGIN;


--------------------레시피정보------------------------------------
CREATE SEQUENCE RECIPE_ID_SEQ START WITH 195454

DROP SEQUENCE VIEW_SEQ;
CREATE SEQUENCE VIEW_SEQ;

-


CREATE TABLE RECIPE_INFO(
   RECIPE_ID NUMBER PRIMARY KEY,--레시피코드
   RECIPE_NM_KO VARCHAR2(400),  --레시피이름
   SUMRY VARCHAR2(2000),        --간략소개
   NATION_CODE NUMBER,          --유형코드
   NATION_NM VARCHAR2(400),    --유형분류
   TY_CODE NUMBER,             --음식분류코드
   TY_NM VARCHAR2(500),       --음식분류
   COOKING_TIME NUMBER,  --조리시간
   CALORIE VARCHAR2(500),       --칼로리
   QNT VARCHAR2(500),           --분량
   LEVEL_NM VARCHAR2(500),       --난이도
   IRDNT_CODE VARCHAR2(500),    --재료별 분류명
   IMG_URL CLOB,      --대표이미지URL
   DET_URL VARCHAR2(4000)       --상세URL
  
   
);


--조회수추가
ALTER TABLE RECIPE_INFO
ADD (VIEWS NUMBER);
--id추가요
ALTER TABLE RECIPE_INFO
ADD (ID VARCHAR2(100));

--레시피정보 전체조회
SELECT * FROM RECIPE_INFO ORDER BY RECIPE_ID ASC;


---------------레시피재료-----------------

CREATE TABLE RECIPE_MATERIAL(
--   레시피코드
   RECIPE_ID NUMBER,
--   재료순번   
   IRDNT_SN NUMBER ,
--    재료명
   IRDNT_NM VARCHAR2(2000),
--    재료용량
   IRDNT_CPCTY VARCHAR2(2000),
--    재료타입 코드
   IRDNT_TY_CODE VARCHAR2(2000),
--    재료 타입명
   IRDNT_TY_NM VARCHAR2(2000)
   
  
);


--price추가요
ALTER TABLE RECIPE_MATERIAL
ADD (PRICE NUMBER);
--재료테이블 조회용
SELECT * FROM RECIPE_MATERIAL ORDER BY RECIPE_ID ASC;

----------------냉장고----------------
CREATE TABLE MY_REFRIGERATOR(
   ID VARCHAR2(100) NOT NULL,
--    재료명
      IRDNT_NM VARCHAR2(2000)
  
);
--냉장고에 내재료 조회용
SELECT * FROM MY_REFRIGERATOR ;


-----------------레시피과정------------------
CREATE TABLE RECIPE_PROCESS(
-- 레시피 코드
   RECIPE_ID NUMBER,
--    요리설명순서
   COOKING_NO NUMBER,
--   요리설명
   COOKING_DC VARCHAR2(2000),
--  과정 이미지 URL
   STRE_STEP_IMAGE_URL VARCHAR2(4000),
--  과정팁
   STER_TIP VARCHAR2(4000)

)

--과정조회용
SELECT * FROM RECIPE_PROCESS 

-------------찜테이블
CREATE SEQUENCE ZZIMSEQ;

CREATE TABLE ZZIM (
SEQ NUMBER NOT NULL,
ID VARCHAR2(100) NOT NULL ,    -- USERID
RECIPE_ID NUMBER NOT NULL,--레시피코드
RECIPE_NM_KO VARCHAR2(400) NOT NULL,
PRIMARY KEY(ID,RECIPE_ID,RECIPE_NM_KO),
CONSTRAINT CON_ZZIMID FOREIGN KEY(ID) REFERENCES LOGIN(ID),
CONSTRAINT CON_ZZIMRECIP FOREIGN KEY(RECIPE_ID) REFERENCES RECIPE_INFO(RECIPE_ID)
);


--찜조회용
select * from zzim;

-------mainhomepage.jsp  저장방법3가지 모두 실행 후 
UPDATE RECIPE_INFO SET VIEWS=0 WHERE VIEWS is null;
UPDATE RECIPE_INFO SET ID='AD'WHERE ID is null;
UPDATE RECIPE_MATERIAL SET PRICE=1000 WHERE PRICE=0;

