DROP TABLE PAYMENT;
DROP SEQUENCE PAYMENTSEQ;

CREATE SEQUENCE PAYMENTSEQ;

CREATE TABLE PAYMENT(
   PAYSEQ NUMBER PRIMARY KEY,
   ID VARCHAR2(100) NOT NULL,
   MATER VARCHAR2(100) NOT NULL,
   PRICE NUMBER NOT NULL,
   PAYDATE DATE NOT NULL,
   PLACE VARCHAR2(1000) NOT NULL
);

INSERT INTO PAYMENT VALUES(PAYMENTSEQ.NEXTVAL,'ASDF','김치','1000',SYSDATE,'서울특별시 중랑구 망우동');

SELECT * FROM PAYMENT;