DROP SEQUENCE MDBOARDSEQ;
DROP TABLE MDBORAD;

CREATE SEQUENCE MDBOARDSEQ;

--번호, 작성자, 제목, 내용, 작성일
CREATE TABLE MDBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(1000) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE FROM MDBOARD;

INSERT INTO MDBOARD VALUES (MDBOARDSEQ.NEXTVAL,'작가','TEST 제목','TEST 내용',SYSDATE);
INSERT INTO MDBOARD VALUES (MDBOARDSEQ.NEXTVAL,'작가','TEST 제목','TEST 내용',SYSDATE);

