DROP TABLE LOGIN;
DROP SEQUENCE LOGINSEQ;

CREATE SEQUENCE LOGINSEQ;

CREATE TABLE LOGIN(
	USERSEQ NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	ID VARCHAR2(100) NOT NULL,
	PW VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	ADDR VARCHAR2(1000) NOT NULL,
	CONSTRAINT CON_ID UNIQUE(ID)
);

INSERT INTO LOGIN
VALUES(LOGINSEQ.NEXTVAL,'정햇나라','ASDF','ASDF','ASDF@ASDF','경기도 성남시 중원구');

SELECT * FROM LOGIN;



