DROP TABLE RECIPE_INFO;
DROP SEQUENCE RECIPE_ID_SEQ;
DROP SEQUENCE VIEW_SEQ;

CREATE SEQUENCE RECIPE_ID_SEQ START WITH 195454

CREATE SEQUENCE VIEW_SEQ;




CREATE TABLE RECIPE_INFO(
   RECIPE_ID NUMBER PRIMARY KEY,--레시피코드
   RECIPE_NM_KO VARCHAR2(400),  --레시피이름
   SUMRY VARCHAR2(2000),        --간략소개
   NATION_CODE NUMBER,          --유형코드
   NATION_NM VARCHAR2(400),    --유형분류
   TY_CODE NUMBER,             --음식분류코드
   TY_NM VARCHAR2(500),       --음식분류
   COOKING_TIME NUMBER,  --조리시간
   CALORIE VARCHAR2(500),       --칼로리
   QNT VARCHAR2(500),           --분량
   LEVEL_NM VARCHAR2(500),       --난이도
   IRDNT_CODE VARCHAR2(500),    --재료별 분류명
   IMG_URL CLOB,      --대표이미지URL
   DET_URL VARCHAR2(4000)       --상세URL
  
   
);


--조회수추가
ALTER TABLE RECIPE_INFO
ADD (VIEWS NUMBER);
--id추가요
ALTER TABLE RECIPE_INFO
ADD (ID VARCHAR2(100));




--NULL값 없데이트 mainhomepage.jsp 에서 저장방법3개 모두 실행 후-- 

UPDATE RECIPE_INFO SET VIEWS=0 WHERE VIEWS is null;
UPDATE RECIPE_INFO SET ID='AD'WHERE ID is null;

--레시피정보 전체조회
--SELECT * FROM RECIPE_INFO ORDER BY RECIPE_ID ASC;

--가장마지막 recipe_id조회
--SELECT MAX(RECIPE_ID) FROM RECIPE_INFO;

--사용자가 작성한 레시피 조회용
--SELECT * FROM RECIPE_INFO WHERE ID='yyon8810';
--DELETE FROM RECIPE_INFO WHERE ID='woong30';



-------------------레시피재료--------------------------------

DROP TABLE RECIPE_MATERIAL;

CREATE TABLE RECIPE_MATERIAL(
--   레시피코드
   RECIPE_ID NUMBER,
--   재료순번   
   IRDNT_SN NUMBER ,
--    재료명
   IRDNT_NM VARCHAR2(2000),
--    재료용량
   IRDNT_CPCTY VARCHAR2(2000),
--    재료타입 코드
   IRDNT_TY_CODE VARCHAR2(2000),
--    재료 타입명
   IRDNT_TY_NM VARCHAR2(2000)
   
  
);



--price추가요
ALTER TABLE RECIPE_MATERIAL
ADD (PRICE NUMBER);

--NULL값 없데이트 json저장후 실행--
UPDATE RECIPE_MATERIAL SET PRICE=1000 WHERE PRICE=0;


--재료테이블 조회용
--SELECT * FROM RECIPE_MATERIAL ORDER BY RECIPE_ID ASC;




--------------------냉장고--------------------------------

DROP TABLE MY_REFRIGERATOR;

CREATE TABLE MY_REFRIGERATOR(
	ID VARCHAR2(100) NOT NULL,
--    재료명
   	IRDNT_NM VARCHAR2(2000)
  
);
--중복제거 
--SELECT DISTINCT * FROM MY_REFRIGERATOR;
--냉장고에 내재료 조회용
--SELECT * FROM MY_REFRIGERATOR ;

----------------- 레시피 과정-----------------------------------
DROP TABLE RECIPE_PROCESS

CREATE TABLE RECIPE_PROCESS(
-- 레시피 코드
	RECIPE_ID NUMBER,
-- 	요리설명순서
	COOKING_NO NUMBER,
--	요리설명
	COOKING_DC VARCHAR2(2000),
--  과정 이미지 URL
	STRE_STEP_IMAGE_URL VARCHAR2(4000),
--  과정팁
	STER_TIP VARCHAR2(4000)
)
--과정조회용
--SELECT * FROM RECIPE_PROCESS 


--SELECT RECIPE_ID,count(*) AS count FROM RECIPE_MATERIAL INNER JOIN MY_REFRIGERATOR ON MY_REFRIGERATOR.IRDNT_NM = RECIPE_MATERIAL.IRDNT_NM group by RECIPE_MATERIAL.RECIPE_ID Order by count DESC
--SELECT RECIPE_ID FROM RECIPE_MATERIAL INNER JOIN MY_REFRIGERATOR ON MY_REFRIGERATOR.IRDNT_NM = RECIPE_MATERIAL.IRDNT_NM group by RECIPE_MATERIAL.RECIPE_ID Order by RECIPE_ID ASC


--sql 테스트란------------------------------------------
